version: "3"
services:
  photoshow:
    container_name: "photoshow"
    build: .
    volumes:
      - photoshow-letsencrypt:/etc/letsencrypt
      - photoshow-data:/opt/PhotoShow
      - photoshow-log:/var/log
    ports:
      - "80:80"
      - "443:443"

volumes:
  photoshow-letsencrypt:
  photoshow-data:
  photoshow-log:  
